# Numpy

El concepto central de NumPy es el ndarray (n-dimensional array). Es como una lista de Python, pero con superpoderes matemáticos y una velocidad radicalmente mayor porque opera en C por debajo.

La diferencia conceptual más importante:

In [2]:
# NumPy array — opera sobre todo el array a la vez (rápido)
import numpy as np

# Lista Python — opera elemento por elemento (lento)
lista = [1, 2, 3, 4, 5]
doble = [x * 2 for x in lista]  # necesitas un loop

arr = np.array([1, 2, 3, 4, 5])
doble = arr * 2  # así de simple, sin loop

**Operaciones recurrentes**

In [3]:
import numpy as np

# Crear arrays
a = np.array([1, 2, 3])           # desde lista
b = np.zeros((3, 4))              # matriz 3x4 de ceros
c = np.ones((2, 2))               # matriz 2x2 de unos
d = np.random.rand(3, 3)          # matriz 3x3 con valores aleatorios entre 0 y 1
e = np.arange(0, 10, 2)           # [0, 2, 4, 6, 8]
f = np.linspace(0, 1, 5)          # [0.0, 0.25, 0.5, 0.75, 1.0]

# Propiedades esenciales
print(d.shape)    # (3, 3) — dimensiones
print(d.dtype)    # float64 — tipo de dato
print(d.ndim)     # 2 — número de dimensiones

# Operaciones matemáticas (todas vectorizadas)
arr = np.array([1, 2, 3, 4, 5], dtype=float)
print(arr.mean())   # 3.0
print(arr.std())    # desviación estándar
print(arr.sum())    # 15.0
print(arr.max())    # 5.0
print(np.sqrt(arr)) # raíz cuadrada de cada elemento

(3, 3)
float64
2
3.0
1.4142135623730951
15.0
5.0
[1.         1.41421356 1.73205081 2.         2.23606798]

**indexing y slicing**

In [ ]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(m[0, 1])      # 2 — fila 0, columna 1
print(m[:, 1])      # [2, 5, 8] — toda la columna 1
print(m[1, :])      # [4, 5, 6] — toda la fila 1
print(m[0:2, 0:2])  # submatriz 2x2 superior izquierda



# Boolean indexing — esto es oro puro en ML
arr = np.array([10, 25, 3, 47, 8, 33])
print(arr[arr > 20])         # [25, 47, 33] — solo los mayores a 20
print(arr[arr % 2 == 0])     # [10, 8] — solo los pares

2
[2 5 8]
[4 5 6]
[[1 2]
 [4 5]]
[25 47 33]
[10  8]

# Pandas

En ML el 80% del tiempo lo pasas limpiando y entendiendo datos. Pandas es donde vive ese trabajo.

El objeto central es el DataFrame: una tabla con filas y columnas con nombre, como un Excel inteligente pero programable.

In [3]:
import pandas as pd

# Crear un DataFrame desde cero
data = {
    'nombre':      ['Ana', 'Luis', 'María', 'Carlos'],
    'edad':        [28, 34, 22, 45],
    'consumo_kwh': [320, 480, 290, 610],
    'tiene_solar': [True, False, False, True]
}
df = pd.DataFrame(data)
print(df)

   nombre  edad  consumo_kwh  tiene_solar
0     Ana    28          320         True
1    Luis    34          480        False
2   María    22          290        False
3  Carlos    45          610         True

**Operaciones recurrentes**

**Exploración inicial — siempre empieza con esto**

In [25]:
df.head()           # primeras 5 filas

   nombre  edad  consumo_kwh  tiene_solar  consumo_diario
0     Ana    28          320         True       10.666667
1    Luis    34          480        False       16.000000
2   María    22          290        False        9.666667
3  Carlos    45          610         True       20.333333

In [26]:
df.tail()           # últimas 5 filas

   nombre  edad  consumo_kwh  tiene_solar  consumo_diario
0     Ana    28          320         True       10.666667
1    Luis    34          480        False       16.000000
2   María    22          290        False        9.666667
3  Carlos    45          610         True       20.333333

In [27]:
df.shape            # (filas, columnas)

(4, 5)

In [28]:
df.info()           # tipos de datos y valores nulos

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nombre          4 non-null      str
 1   edad            4 non-null      int64
 2   consumo_kwh     4 non-null      int64
 3   tiene_solar     4 non-null      bool
 4   consumo_diario  4 non-null      float64
dtypes: bool(1), float64(1), int64(2), str(1)
memory usage: 264.0 bytes

In [29]:
df.describe()       # estadísticas: media, std, min, max, percentiles

            edad  consumo_kwh  consumo_diario
count   4.000000     4.000000        4.000000
mean   32.250000   425.000000       14.166667
std     9.810708   148.884743        4.962825
min    22.000000   290.000000        9.666667
25%    26.500000   312.500000       10.416667
50%    31.000000   400.000000       13.333333
75%    36.750000   512.500000       17.083333
max    45.000000   610.000000       20.333333

In [30]:
# Seleccionar columnas
df['edad']                        # una columna → Serie

0    28
1    34
2    22
3    45
Name: edad, dtype: int64

In [31]:
df[['nombre', 'consumo_kwh']]     # varias columnas → DataFrame

   nombre  consumo_kwh
0     Ana          320
1    Luis          480
2   María          290
3  Carlos          610

In [32]:
# Filtrar filas
df[df['edad'] > 30]

   nombre  edad  consumo_kwh  tiene_solar  consumo_diario
1    Luis    34          480        False       16.000000
3  Carlos    45          610         True       20.333333

In [33]:
# Filtrar filas
df[(df['edad'] > 25) & (df['consumo_kwh'] < 500)]

  nombre  edad  consumo_kwh  tiene_solar  consumo_diario
0    Ana    28          320         True       10.666667
1   Luis    34          480        False       16.000000

In [34]:
# Nueva columna calculada
df['consumo_diario'] = df['consumo_kwh'] / 30

**Valores nulos — crítico en ML**

In [21]:
df.isnull().sum()                        # cuántos nulos por columna

nombre            0
edad              0
consumo_kwh       0
tiene_solar       0
consumo_diario    0
dtype: int64

In [22]:
df.dropna()                              # eliminar filas con nulos

   nombre  edad  consumo_kwh  tiene_solar  consumo_diario
0     Ana    28          320         True       10.666667
1    Luis    34          480        False       16.000000
2   María    22          290        False        9.666667
3  Carlos    45          610         True       20.333333

In [23]:
df.fillna(df.mean(numeric_only=True))    # rellenar nulos con la media (solo columnas numéricas)

   nombre  edad  consumo_kwh  tiene_solar  consumo_diario
0     Ana    28          320         True       10.666667
1    Luis    34          480        False       16.000000
2   María    22          290        False        9.666667
3  Carlos    45          610         True       20.333333

In [24]:
# Agrupar — equivalente a GROUP BY en SQL
df.groupby('tiene_solar')['consumo_kwh'].mean()

tiene_solar
False    385.0
True     465.0
Name: consumo_kwh, dtype: float64

# EJERCICIOS DE APLICACIÓN

In [1]:
import numpy as np

# 1. Crea un array con los números del 1 al 20
arr = np.arange(1, 21)
print(arr)
# 2. Calcula su media, desviación estándar y suma
print("Media: " + str(np.mean(arr)))
# 3. Filtra solo los números que sean mayores a la media
filtered_arr = arr[arr > np.mean(arr)]
print("Numeros mayores a la media: " + str(filtered_arr))
# 4. Eleva al cuadrado solo los números impares
print("Numeros impares al cuadrado: " + str(arr[arr % 2 != 0] ** 2))
# (pista: arr % 2 != 0 te da los impares)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Media: 10.5
Numeros mayores a la media: [11 12 13 14 15 16 17 18 19 20]
Numeros impares al cuadrado: [  1   9  25  49  81 121 169 225 289 361]

In [2]:
import pandas as pd

# Tienes datos de consumo eléctrico de 6 casas durante un mes
datos = {
    'casa':    ['Casa A', 'Casa B', 'Casa C', 'Casa D', 'Casa E', 'Casa F'],
    'kwh_mes': [320, 480, None, 610, 290, 540],
    'personas': [2, 4, 1, 5, 2, 3],
    'zona':    ['norte', 'sur', 'norte', 'sur', 'norte', 'sur']
}
df = pd.DataFrame(datos)

# 1. Explora el DataFrame con head(), info() y describe()
df.head()
df.info()
df.describe()
# 2. ¿Cuál es el consumo promedio por zona?

# 3. Rellena el valor nulo con la mediana de kwh_mes
# 4. Crea una columna 'kwh_por_persona' = kwh_mes / personas
# 5. Filtra las casas donde kwh_por_persona > 100

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   casa      6 non-null      str
 1   kwh_mes   5 non-null      float64
 2   personas  6 non-null      int64
 3   zona      6 non-null      str
dtypes: float64(1), int64(1), str(2)
memory usage: 324.0 bytes

          kwh_mes  personas
count    5.000000  6.000000
mean   448.000000  2.833333
std    138.816426  1.471960
min    290.000000  1.000000
25%    320.000000  2.000000
50%    480.000000  2.500000
75%    540.000000  3.750000
max    610.000000  5.000000